### ISSUE TITLE
Category for parent is not added   from the backend menu

### ISSUE THREAD

**Issue by toome123** [feegleweb/oc-octoshoplite-plugin#2]
When i try to set Parent category of some category , the changes is not saved , and i can't make sub categories .. I can't solve problem ... The source code is the same like this repo ...

**Comment by VadimPolh** [comment]
@toome123 I also encountered this problem , you have managed to solve it ?

**Comment by toome123** [comment]
@VadimPolh No , i still have this problem,and use one level categoriea.. the code for this action is missing in lite version of the plugin.. Please if you solve the problem, share with us..

**Comment by dshoreman** [comment]
This was fixed a long time ago in the full version of Octoshop. I may port the fix over at some point in the future, however I'm currently busy with a mixture of client work and working on Octoshop v2, so I have no plans to update Lite in the near future.

If you need support and updates, help support development and [buy the full version](https://octobercms.com/plugin/feegleweb-octoshop) in the OctoberCMS marketplace.

**Comment by VadimPolh** [comment]
@dshoreman I wrote to you on mail, if you could answer me?

**Comment by hushulin** [comment]
I have this problem too , but , old version for this plugin work ok. can i have the old version plugin? if i can get the old version , what can i do ?

**Comment by dshoreman** [comment]
@hushulin You can download old versions from [the releases page](https://github.com/feegleweb/oc-octoshoplite-plugin/releases).
