### ISSUE TITLE
user / pwd not correct on the demo site

### ISSUE THREAD

**Issue by i3zhe** [feegleweb/oc-octoshoplite-plugin#4]
Hey dude, I'm very interested in this cool plugin, so I wanna take a whole look in the backend. Could you please update the valid user account for the admin section? 

Thanks for the hard work.

**Comment by dshoreman** [comment]
Demo login is fixed now, same login as before. Thanks for letting me know.

**Comment by i3zhe** [comment]
@dshoreman cool, working now. TY
